version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/docs:/app/docs
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=supersecretkey
    networks:
      - internal
  frontend:
    build: ./frontend
    networks:
      - internal
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend
    networks:
      - internal
networks:
  internal:
    driver: bridge